/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FotosRouteImport } from './routes/fotos'
import { Route as FuncionarioRouteImport } from './routes/funcionario'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PCompanyIdRouteImport } from './routes/p.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosRoute = FotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionarioRoute = FuncionarioRouteImport.update({
  id: '/funcionario',
  path: '/funcionario',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PCompanyIdRoute = PCompanyIdRouteImport.update({
  id: '/p/$companyId',
  path: '/p/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fotos': typeof FotosRoute
  '/funcionario': typeof FuncionarioRoute
  '/relatorios': typeof RelatoriosRoute
  '/p/$companyId': typeof PCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fotos': typeof FotosRoute
  '/funcionario': typeof FuncionarioRoute
  '/relatorios': typeof RelatoriosRoute
  '/p/$companyId': typeof PCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fotos': typeof FotosRoute
  '/funcionario': typeof FuncionarioRoute
  '/relatorios': typeof RelatoriosRoute
  '/p/$companyId': typeof PCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fotos' | '/funcionario' | '/relatorios' | '/p/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fotos' | '/funcionario' | '/relatorios' | '/p/$companyId'
  id:
    | '__root__'
    | '/'
    | '/fotos'
    | '/funcionario'
    | '/relatorios'
    | '/p/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FotosRoute: typeof FotosRoute
  FuncionarioRoute: typeof FuncionarioRoute
  RelatoriosRoute: typeof RelatoriosRoute
  PCompanyIdRoute: typeof PCompanyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos': {
      id: '/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof FotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionario': {
      id: '/funcionario'
      path: '/funcionario'
      fullPath: '/funcionario'
      preLoaderRoute: typeof FuncionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$companyId': {
      id: '/p/$companyId'
      path: '/p/$companyId'
      fullPath: '/p/$companyId'
      preLoaderRoute: typeof PCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FotosRoute: FotosRoute,
  FuncionarioRoute: FuncionarioRoute,
  RelatoriosRoute: RelatoriosRoute,
  PCompanyIdRoute: PCompanyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
